import Head from 'next/head';
import CreatePost from '../components/CreatePost';
import Post from '../components/Post';
import axios from 'axios';
import { useEffect, useState } from 'react';

export default function Home() {
  const [posts, setPosts] = useState([]);

  const getPosts = async () => {
    const res = await axios.get('https://posts.zexianli.workers.dev/posts');
    setPosts(res.data.posts);
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="sm:w-4/6 md:w-3/6 lg:w-2/6 mx-auto">
        <div className="my-3 border shadow-md p-2 rounded-md">
          <h3 className="font-semibold text-lg">Create new post</h3>
          <CreatePost setPosts={setPosts} posts={posts} />
        </div>

        <div id="postsContainer">
          {posts.map((post, idx) => (
            <Post
              key={idx}
              username={post.username}
              title={post.title}
              content={post.content}
            />
          ))}
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
